####################################################################
###################### DO NOT EDIT THIS FILE #######################
####################################################################

UNSEEN_WATER = -1
SEEN_WATER = -2
SEEN_SHIP = -3

MISS_MARKER = "o"
HIT_MARKER = "x"
UNSEEN_MARKER = " "

MISS_ID = 0
HIT_ID = 1
SUNK_ID = 2

NORTH = 'n'
SOUTH = 's'
EAST = 'e'
WEST = 'w'